### ISSUE TITLE
Agrupamiento por Tipo, coleccion, temporada

### ISSUE THREAD

**Issue by febatu** [SilverioBernal/MarroquineraMH#1]
Por favor que los agrupamientos se hagan sin tener en cuenta el producto, si no se selecciona.

**Comment by SilverioBernal** [comment]
revisando... en breve te daremos respuesta

**Comment by SilverioBernal** [comment]
Algunos de los cálculos que se piden para Sellthru involucran necesariamente el producto. por lo tanto siempre se debe consultar esta columna. Para mejorar la usabilidad del programa no se permite des-seleccionar la columna de producto y siempre se traera este dato en las consultas.
