### ISSUE TITLE
Error en filtros de Selltrhu

### ISSUE THREAD

**Issue by febatu** [SilverioBernal/MarroquineraMH#2]
En los filtros cuando se selecciona la opción de todas las redes y se selecciona una colección (LIENZO)específica no muestra información, se tiene que seleccionar una red de tiendas(COLOMBIA) y ahí sí
![cubo linx](https://user-images.githubusercontent.com/32395544/31249209-158690f0-a9dc-11e7-9cdf-f7ff9c78a91c.jpg)
![sellthru](https://user-images.githubusercontent.com/32395544/31249208-15858a98-a9dc-11e7-988a-9b07f0ed03bd.jpg)

 muestra información, otra situación es que no trae la información de todas las tiendas solo muestra aquellas que tienen venta y no las que tienen stock. anexo imágenes del reporte Sellthru y de nuestros cubos.

Quedo atento.

Gracias!!

**Comment by SilverioBernal** [comment]
-Se crea funcionabilidad para asociar redes de tiendas a los usuarios de webmiddle.
-se mejoran los filtros para que si no se selecciona una red de tiendas muestre las tiendas de las redes asociadas al usuario. 
-Es necesario que se asocien los usuarios a al menos una red de tendas para poder visualizar los reportes de inventario y sell thru. esto se hace desde la opcion Usuarios. 
-se modifica la consulta para que no muestre solamente la informacion de las tiendas con ventas sino tambien para aquellos que no registran ventas
